
stages:
  - test

test:linux:
  stage: test
  tags:
    - linux
  script:
    - export CURRENT_BUILD_PATH=$(pwd)
    - export GOPATH=$CURRENT_BUILD_PATH
    - mkdir -p github.com/itchio/wharf
    - rsync -az . github.com/itchio/wharf
    - go get -v -x -d -t github.com/itchio/wharf/...
    - go test -v -x github.com/itchio/wharf/...

test:win32:
  stage: test
  tags:
    - win32
  script:
    - export CURRENT_BUILD_PATH=$(pwd)
    - export GOPATH=$CURRENT_BUILD_PATH
    - mkdir -p github.com/itchio/wharf
    - rsync -az . github.com/itchio/wharf
    - go get -v -x -d -t github.com/itchio/wharf/...
    - go test -v -x github.com/itchio/wharf/...
